name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          # Ensure tzdata is present for date parsing on some runners
          pip install tzdata

      - name: Lint (ruff)
        run: ruff check .

      - name: Type-check (mypy)
        run: mypy app

      - name: Run tests (pytest)
        run: pytest -q
